# Generated by Django 4.0.6 on 2023-08-10 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ward_admin', models.BooleanField(default=False)),
                ('is_edu_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master.ward')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('birth_cert_no', models.CharField(max_length=100)),
                ('admission_no', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('f', 'Female'), ('m', 'Male')], max_length=2)),
                ('institution', models.CharField(max_length=100)),
                ('bank', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master.financialyear')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master.ward')),
            ],
        ),
        migrations.CreateModel(
            name='Allocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master.financialyear')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master.ward')),
            ],
        ),
    ]
