# Generated by Django 4.0.6 on 2023-08-10 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allocations',
            new_name='Allocation',
        ),
    ]
