# Generated by Django 4.0.6 on 2023-08-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kcbmsuser',
            name='is_accountant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kcbmsuser',
            name='is_edu_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kcbmsuser',
            name='is_ward_admin',
            field=models.BooleanField(default=False),
        ),
    ]
