# Generated by Django 4.0.5 on 2023-08-14 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0002_rename_allocations_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='disability_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='family_status',
            field=models.CharField(choices=[('o', 'Orphan'), ('s', 'Single Parents'), ('b', 'Both Parents')], default='o', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allocation',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.financialyear'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.ward'),
        ),
        migrations.AlterField(
            model_name='application',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.financialyear'),
        ),
        migrations.AlterField(
            model_name='application',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.ward'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
