# Generated by Django 4.0.6 on 2023-08-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_application_disability_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_accountant',
            field=models.BooleanField(default=False),
        ),
    ]
